# Generated by Django 3.2 on 2021-04-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_routine_scheduler_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='time',
            field=models.TimeField(),
        ),
    ]
